dataset_name: humanual_book
app_name: Humanual-Book
prompt_is_json_string: false
prompt_metadata_is_json_string: true
metadata_is_json_string: true
persona_enrichment:
  use_metadata_fields:
    - rating
    - verified_purchase
    - helpful_vote

